# GOEDUHUB | Task - 4 | Numpy | Reg-ID : GO_STP_2134|

__1) Import the numpy package under the name np and Print the numpy version and the configuration__


In [2]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
None


__2) Create a null vector of size 10__

In [7]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


__3) Create Simple 1-D array and check type and check data types in array__


In [8]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int32


__4) How to find number of dimensions, bytes per element and bytes of memory used?__


In [9]:
print("The size of an array",a.size)
print("Size of an element in array",a.itemsize)
print("bytes of memory used:",a.size*a.itemsize)

The size of an array 5
Size of an element in array 4
bytes of memory used: 20


__5) Create a null vector of size 10 but the fifth value which is 1__


In [10]:
a=np.zeros(10)
a[4]=5
print(a)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


__6) Create a vector with values ranging from 10 to 49__


In [12]:
#print(np.range(10,49))
print(np.arange(10,49))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


__7) Reverse a vector (first element becomes last)__


In [16]:
x=np.arange(10,20)
print(x)
print("Reversed vector",x[::-1])

[10 11 12 13 14 15 16 17 18 19]
Reversed vector [19 18 17 16 15 14 13 12 11 10]


__8) Create a 3x3 matrix with values ranging from 0 to 8__


In [18]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


__9) Find indices of non-zero elements from [1,2,0,0,4,0]__


In [20]:
a=[1,2,0,0,4,0]
print([i for i in range(len(a)) if a[i]==0])

[2, 3, 5]


__10) Create a 3x3 identity matrix__


In [23]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


__11) Create a 3x3x3 array with random values__


In [28]:
print(np.random.random((3,3,3)))

[[[0.52672674 0.20394705 0.78161457]
  [0.13759745 0.08542231 0.58344229]
  [0.7060722  0.88184198 0.72244217]]

 [[0.67138253 0.60511908 0.79416286]
  [0.10021965 0.38074487 0.94258258]
  [0.72657275 0.94950616 0.8126249 ]]

 [[0.94807247 0.45954123 0.98915735]
  [0.53206349 0.44875878 0.83519233]
  [0.14878579 0.19095495 0.63782109]]]


In [25]:
print(np.random.randint(10,20,27).reshape(3,3,3))

[[[19 16 10]
  [19 16 16]
  [16 16 13]]

 [[17 15 13]
  [18 19 10]
  [12 15 14]]

 [[14 15 11]
  [11 14 17]
  [15 16 13]]]


__12) Create a 10x10 array with random values and find the minimum and maximum values__

In [33]:
a=np.random.randint(10,20,100).reshape(10,10)
print(a)
print()
print("The Maximum Value:",a.max())
print("The Minimum Value:",a.min())


[[15 15 13 11 14 15 13 14 13 16]
 [16 16 14 15 11 16 18 14 17 15]
 [16 10 16 17 19 10 17 15 14 13]
 [17 11 12 17 14 13 12 18 14 17]
 [18 17 17 18 10 16 16 19 12 11]
 [10 11 10 18 10 18 18 11 19 15]
 [16 19 17 15 14 17 11 14 18 18]
 [10 17 14 11 10 10 13 16 10 19]
 [19 17 11 12 11 17 12 15 16 10]
 [19 15 10 16 17 18 16 13 13 12]]

The Maximum Value: 19
The Minimum Value: 10


__13) Create a random vector of size 30 and find the mean value__


In [37]:
x=np.random.random(30)
print(x)
print()
print("The Mean of X is : ",x.mean())

[0.3929469  0.54204443 0.38818806 0.14804411 0.55340359 0.69052309
 0.58577852 0.0556429  0.34229482 0.14559023 0.87337511 0.44383449
 0.5006041  0.74570388 0.24604633 0.18371458 0.29558726 0.36355797
 0.52150958 0.71528753 0.43331994 0.61748821 0.70407477 0.74861747
 0.14332839 0.8837824  0.10087151 0.80212832 0.94016064 0.5933926 ]

The Mean of X is :  0.49002805764595736


__14) Create a 2d array with 1 on the border and 0 inside__


In [41]:
x=np.ones((5,5))
print(x)
print()
print("New array:")
print()
x[1:4,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

New array:

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
x=int(input())
y=int(input())
z=np.ones((x,y))
z[1:-1,1:-1]=0
print(z)

8
8
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


__15) How to add a border (filled with 0's) around an existing array?__


In [48]:
x=np.random.randint(10,20,25).reshape(5,5)
print(x)
print()
print("New array:")
x[0:-1,0]=0
x[0,0:-1]=0
x[-1,0:-1]=0
x[0:,-1]=0
print(x)

[[13 12 12 19 15]
 [10 19 17 10 16]
 [16 17 13 14 12]
 [18 10 11 14 17]
 [14 13 12 18 14]]

New array:
[[ 0  0  0  0  0]
 [ 0 19 17 10  0]
 [ 0 17 13 14  0]
 [ 0 10 11 14  0]
 [ 0  0  0  0  0]]


In [49]:
m=int(input())
n=int(input())
x=np.random.randint(10,20,m*n).reshape(m,n)
print(x)
print()
print("New array:")
x[0:-1,0]=0
x[0,0:-1]=0
x[-1,0:-1]=0
x[0:,-1]=0
print(x)

4
5
[[14 11 17 15 13]
 [18 13 17 15 18]
 [14 16 13 11 16]
 [16 18 15 15 14]]

New array:
[[ 0  0  0  0  0]
 [ 0 13 17 15  0]
 [ 0 16 13 11  0]
 [ 0  0  0  0  0]]


__16) How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?__  


- Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

- Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20




In [66]:
a=[[1, 2, 3, 4, 5, 6, 7], [ 8, 9, 10, 11, 12, 13, 14]]
print(a)
print()
print("Get 13:")
print(a[1][-2])
print()
print("Get First row only:")
print(a[0])
print()
print("Get 3rd column only")
print(a[0][2],a[1][2])
print()
print("Get 2,4,6:")
print([a[0][i] for i in range(1,7,2)])
print()
print("Replace 13 by 20:")
a[1][-2]=20
print(a)


[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]]

Get 13:
13

Get First row only:
[1, 2, 3, 4, 5, 6, 7]

Get 3rd column only
3 10

Get 2,4,6:
[2, 4, 6]

Replace 13 by 20:
[[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 20, 14]]


__17) How to Convert a 1D array to a 2D array with 2 rows__



In [69]:
x=np.array([1,2,3,4,5,56])
print(x)
print(x.reshape(2,3))


[ 1  2  3  4  5 56]
[[ 1  2  3]
 [ 4  5 56]]


__18) Create the following pattern without hardcoding. Use only numpy functions and the below input array a.__

- Input:a = np.array([1,2,3])`
- Desired Output:  
    array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [70]:
a=np.array([1,2,3])
print(np.r_[np.repeat(a,3),np.tile(a,3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


__19) Write a program to show how Numpy taking less memory compared to Python List?__


In [71]:
l=range(1000)
import sys
a=10
print(sys.getsizeof(a))
print("List consumed memory size",sys.getsizeof(a)*len(l))
a1=np.arange(1000)
print("Numpy Memory consumed size:",a1.size*a1.itemsize)

28
List consumed memory size 28000
Numpy Memory consumed size: 4000


__20) Write a program to show how Numpy taking less time compared to Python List?__



In [72]:
import time
import sys

size=100000
l1=range(size)
l2=range(size)

start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

n1=np.arange(100000)
n2=np.arange(100000)

start=time.time()
result_=n1+n2
print((time.time()-start)*1000)

27.98008918762207
0.0
