# NUMPY | 26-05-2021 |

In [1]:
import numpy as np

__Create 1-D array__

In [2]:
a=np.array([1,2,4])
print(a)
print(type(a))

[1 2 4]
<class 'numpy.ndarray'>


__Create Multi Dimensional Array__

In [15]:
b=np.array([[1,2,3],[2,3,4]])
print(b)
print(b.dtype)
print()
a=np.array([[1,2,3],[2,3,4],[3,4,5]])
print(a)
print(a.dtype)

[[1 2 3]
 [2 3 4]]
int32

[[1 2 3]
 [2 3 4]
 [3 4 5]]
int32


__zeros()__

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

__arange()__

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(2,3,0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

__linspace__

In [11]:
np.linspace(1,4,5)

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [13]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

__indices()__

In [16]:
np.indices((2,3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

### Memory taken by list and a numpy

In [20]:
l=range(1000)
import sys
a=10
print(sys.getsizeof(a))
print("List consumed memory size",sys.getsizeof(a)*len(l))
a1=np.arange(1000)
print("Numpy Memory consumed size:",a1.size*a1.itemsize)

28
List consumed memory size 28000
Numpy Memory consumed size: 4000


### Numpy vs List speed

In [23]:
import time
import sys

size=100000
l1=range(size)
l2=range(size)

start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print((time.time()-start)*1000)

n1=np.arange(100000)
n2=np.arange(100000)

start=time.time()
result_=n1+n2
print((time.time()-start)*1000)

34.98268127441406
0.99945068359375


## Numpy Operations

In [24]:
a=np.array([[1,2,3],[2,3,4]])
print(a.ndim)

2


In [25]:
print(a.itemsize)

4


In [27]:
print(a.dtype)

int32


In [28]:
print(a.shape)

(2, 3)


In [29]:
print(a.size)

6


In [32]:
print(a.reshape(3,2))
print()
print(a.reshape(2,3))


[[1 2]
 [3 2]
 [3 4]]

[[1 2 3]
 [2 3 4]]


In [52]:
np.reshape(a,(2,3))

array([[1, 2, 3],
       [2, 3, 4]])

In [53]:
np.reshape(a,(3,2))

array([[1, 2],
       [3, 2],
       [3, 4]])

In [57]:
np.reshape(a,6)

array([1, 2, 3, 2, 3, 4])

In [62]:
w=np.reshape(a,a.size)
print(w)
print(type(w))

[1 2 3 2 3 4]
<class 'numpy.ndarray'>


In [58]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [61]:
x=a.flatten()
print(x)
print(type(x))
print(x.dtype)

[1 2 3 2 3 4]
<class 'numpy.ndarray'>
int32


## Slicing

In [33]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [40]:
print(a[0,0])
print()
print(a[0:2,1:3])
print()
print(a[0:2,-1])
print()
print(a[-1,:])

1

[[2 3]
 [3 4]]

[3 4]

[2 3 4]


## Min,max and sum

In [41]:
print(a.min())
print(a.sum())
print(a.max())

1
15
4


In [42]:
print(a)

[[1 2 3]
 [2 3 4]]


In [43]:
print(np.sum(a,axis=0))

[3 5 7]


In [44]:
#row wise sum
print(np.sum(a,axis=1))

[6 9]


## Mathematical operations

In [47]:
x=np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])

print(x)
print()
print(y)
print()
print(x+y)
print()
print(np.add(x,y))

[[1 2]
 [3 4]]

[[4 5]
 [6 7]]

[[ 5  7]
 [ 9 11]]

[[ 5  7]
 [ 9 11]]


In [51]:
print(x-y,x*y,y/x,sep='\n')

[[-3 -3]
 [-3 -3]]
[[ 4 10]
 [18 28]]
[[4.   2.5 ]
 [2.   1.75]]
